Major refactoring
Prepping to give chezmoi a go again

diff --git a/available/functions b/available/functions
--- a/available/functions
+++ b/available/functions
@@ -2,13 +2,16 @@
 
 # OpenSSL
 get-chain() {
-    echo | openssl s_client -connect ${1}:${2:-443} -showcerts 2>/dev/null | \
+    echo | openssl s_client -connect ${1}:${2:-443} -showcerts 2>/dev/null |
         awk '/-----BEGIN/{out=sprintf("'${1}'-%02d.cer",++count); p=1} /-----END/ {print > out; p=0} p {print > out}'
 }
 
 cert2key() {
-    N=$( (openssl x509 -in $1 -noout -modulus | \
-        openssl md5; openssl rsa -in $2 -noout -modulus | openssl md5) | uniq | wc -l )
+    N=$( (
+        openssl x509 -in $1 -noout -modulus |
+            openssl md5
+        openssl rsa -in $2 -noout -modulus | openssl md5
+    ) | uniq | wc -l)
     if [ $N == 1 ]; then
         echo "Cert and key MATCH"
     else
@@ -18,12 +21,12 @@ cert2key() {
 
 show-p12cert() { openssl pkcs12 -in $1 -nokeys -clcerts | openssl x509 -noout -text; }
 
-dump-p7certs() { openssl pkcs7 -in $1 -print_certs | \
+dump-p7certs() { openssl pkcs7 -in $1 -print_certs |
     awk '/-----BEGIN/ {out=sprintf("'${1%.*}'-%02d.cer",++count); p=1} /-----END/ {print > out; p=0} p {print > out}'; }
 
 fix-cert-name() {
-    openssl x509 -in "${1}" -noout -subject | \
-        awk -F' = ' '{print $NF}' | \
+    openssl x509 -in "${1}" -noout -subject |
+        awk -F' = ' '{print $NF}' |
         sed '
             s/.*/\L&/        # conver to lowercase (requires GNU sed!)
             s/ - */-/g       # condense hyphenations
@@ -56,7 +59,6 @@ ssh-alias
 ## For hosts where I immediately sudo su -
 root() { ssh $@ -t "sudo su -"; }
 
-
 # Docker
 docker-flatten() {
     docker export $(docker run -d ${1} /bin/bash) | docker import – ${2}
@@ -70,7 +72,7 @@ docker-tags() {
 ## Check the balance of Docker's wonderful rate limit
 docker-rl() {
     TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | jq -r .token)
-    curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest 2>&1 | \
+    curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest 2>&1 |
         grep ratelimit-
 }
 
@@ -82,34 +84,37 @@ docker-rl() {
 ## TODO: deal with spaces in directory names
 git-remotes() {
     for DIR in $(find . -type d); do
-        [ -d "$DIR"/.git ] && \
+        [ -d "$DIR"/.git ] &&
             (cd "$DIR" && printf "${DIR}: [%s] %s\n" $(git remote -v | awk '{print $1" "$2}' | uniq))
     done
 }
 
 getgit() {
-    (cd ${D}; if [[ -d .git ]]; then
-        printf "${PWD}, %s\n" $(git config --get remote.origin.url)
-    else
-        for D in $(find . -maxdepth 1 -mindepth 1 -type d -regex '.*/[^.-].*' -printf '%f\n'); do
-            getgit ${D}
-        done
-    fi)
+    (
+        cd ${D}
+        if [[ -d .git ]]; then
+            printf "${PWD}, %s\n" $(git config --get remote.origin.url)
+        else
+            for D in $(find . -maxdepth 1 -mindepth 1 -type d -regex '.*/[^.-].*' -printf '%f\n'); do
+                getgit ${D}
+            done
+        fi
+    )
 }
 
 ## Assumes jq is available!
 ghostars() {
     for ORG in $@; do
-        printf "$ORG: %s\n" $(curl -s https://api.github.com/orgs/$ORG/repos | \
-        jq '[ .[] | .stargazers_count ] | add')
+        printf "$ORG: %s\n" $(curl -s https://api.github.com/orgs/$ORG/repos |
+            jq '[ .[] | .stargazers_count ] | add')
     done
 }
 
-gitlarge () {
+gitlarge() {
     # List objects in the repository sorted by size
     # (not necessarily the largest files, but the largest objects)
     # Note: this will not work on a bare repository
-    git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | \
+    git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |
         grep -v tag | sort -k3nr
 }
 
@@ -118,14 +123,19 @@ ls-() {
     ls -$@
 }
 
+rm-() {
+    rm -$@
+}
+
 ## Send/receive files over netcat (port hardcoded for simplicity)
 send() {
-    HOST=$1; shift
+    HOST=$1
+    shift
     echo "Sending to $HOST:10301..."
     if [ $(which pv) ]; then
         tar czf - $@ | pv | nc -Nv $HOST 10301
     else
-        1>&2 echo "pv not found, so no stats for you!"
+        echo 1>&2 "pv not found, so no stats for you!"
         tar cvzf - $@ | nc -Nv $HOST 10301
     fi
     echo "Done"
@@ -160,13 +170,13 @@ recv() {
 # }
 
 randh() {
-    LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c${1:-16}
+    LC_ALL=C tr -dc 'a-f0-9' </dev/urandom | head -c${1:-16}
 }
 
 randa() {
-    LC_ALL=C tr -dc '[:alnum:]' < /dev/urandom | head -c${1:-16}
+    LC_ALL=C tr -dc '[:alnum:]' </dev/urandom | head -c${1:-16}
 }
 
 randg() {
-    LC_ALL=C tr -dc '[:graph:]' < /dev/urandom | head -c${1:-16}
+    LC_ALL=C tr -dc '[:graph:]' </dev/urandom | head -c${1:-16}
 }
